server {
  listen 80;

  # Serve the React frontend
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }

  # Proxy API requests to internal backend
  location /api/ {
    proxy_pass http://url-shortener-backend:8000/;
    proxy_set_header Host $host;
  }
}
